# monitoring/alertmanager.yml
# Alert Manager configuration

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@trading-bot.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Example: Slack notification (uncomment and configure)
  # - name: 'slack-notifications'
  #   slack_configs:
  #     - api_url: 'YOUR_SLACK_WEBHOOK_URL'
  #       channel: '#trading-alerts'
  #       title: 'Trading Bot Alert'
  #       text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']