# monitoring/prometheus.yml
# Prometheus configuration for Solana trading bot monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load alerting rules
rule_files:
  - "alerts.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Scrape the Solana trading bot metrics
  - job_name: 'solana-trading-bot'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Bot's metrics server
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']